DROP TABLE IF EXISTS `participant`;

CREATE TABLE `participant_summary` (
    `participant_id` BIGINT NOT NULL,
    `match_id` VARCHAR(20) NOT NULL,
    `puuid` VARCHAR(100) NOT NULL,
    `riot_id_game_name` VARCHAR(50),
    `riot_id_tagline` VARCHAR(20),
    `profile_icon` INT,
    `team_id` INT NOT NULL,
    `champion_id` INT NOT NULL,
    `champion_name` VARCHAR(50),
    `champ_level` INT,
    `kills` SMALLINT,
    `deaths` SMALLINT,
    `assists` SMALLINT,
    `kda` DECIMAL(5,2) GENERATED ALWAYS AS (ROUND((kills + assists) / NULLIF(deaths, 0), 2)) VIRTUAL,
    `total_minions_killed` INT,
    `gold_earned` INT,
    `item0` INT,
    `item1` INT,
    `item2` INT,
    `item3` INT,
    `item4` INT,
    `item5` INT,
    `item6` INT,
    `summoner1_id` INT,
    `summoner2_id` INT,
    `vision_score` INT,
    `wards_placed` INT,
    `wards_killed` INT,
    `stealth_wards_placed` INT,
    `detector_wards_placed` INT,
    `vision_wards_bought` INT,
    `team_position` VARCHAR(20),
    `individual_position` VARCHAR(20),
    `physical_damage_dealt_to_champions` INT,
    `magic_damage_dealt_to_champions` INT,
    `true_damage_dealt_to_champions` INT,
    `total_damage_taken` INT,
    `double_kills` INT,
    `triple_kills` INT,
    `quadra_kills` INT,
    `penta_kills` INT,
    `win` BOOLEAN,
    `created_at` DATETIME NOT NULL,
    `modified_at` DATETIME NOT NULL,
    PRIMARY KEY (`participant_id`, `match_id`)
);

CREATE TABLE `participant_analysis` (
    `participant_id` BIGINT NOT NULL,
    `match_id` VARCHAR(20) NOT NULL,
    `damage_dealt_to_champions` INT, 
    `damage_dealt_to_buildings` INT,
    `damage_dealt_to_objectives` INT,
    `damage_dealt_to_turrets` INT,
    `total_time_cc_dealt` INT,
    `jungle_cs_before_10_min` FLOAT,
    `lane_minions_first_10_min` INT,
    `scuttle_crab_kills` INT,
    `quick_solo_kills` INT,
    `kills_on_laners_early_jungle` INT,
    `stat_perks_defense` INT NULL,
    `stat_perks_flex` INT NULL,
    `stat_perks_offense` INT NULL,
    `created_at` DATETIME NOT NULL,
    `modified_at` DATETIME NOT NULL,
    PRIMARY KEY (`participant_id`, `match_id`)
);

CREATE TABLE `participant_perk` (
    `participant_id` BIGINT NOT NULL,
    `match_id` VARCHAR(20) NOT NULL,
    `style_type` VARCHAR(10) NOT NULL,
    `style` INT NULL,
    `perk_id` INT NULL,
    `var1` INT NULL,
    `var2` INT NULL,
    `var3` INT NULL,
    `created_at` DATETIME NOT NULL,
    `modified_at` DATETIME NOT NULL,
    PRIMARY KEY (`participant_id`, `match_id`, `style_type`)
); 