DROP TABLE IF EXISTS `participant`;

CREATE TABLE `participant_summary` (
    `participant_id` BIGINT NOT NULL NOT NULL,
    `match_id` VARCHAR(20) NOT NULL NOT NULL,
    `puuid` VARCHAR(100) NOT NULL NOT NULL,
    `riot_id_game_name` VARCHAR(50) NOT NULL,
    `riot_id_tagline` VARCHAR(20) NOT NULL,
    `profile_icon` INT NOT NULL,
    `team_id` INT NOT NULL NOT NULL,
    `champion_id` INT NOT NULL NOT NULL,
    `champion_name` VARCHAR(50) NOT NULL,
    `champ_level` INT NOT NULL,
    `kills` SMALLINT NOT NULL,
    `deaths` SMALLINT NOT NULL,
    `assists` SMALLINT NOT NULL,
    `total_minions_killed` INT NOT NULL,
    `gold_earned` INT NOT NULL,
    `item0` INT NOT NULL,
    `item1` INT NOT NULL,
    `item2` INT NOT NULL,
    `item3` INT NOT NULL,
    `item4` INT NOT NULL,
    `item5` INT NOT NULL,
    `item6` INT NOT NULL,
    `summoner1_id` INT NOT NULL,
    `summoner2_id` INT NOT NULL,
    `vision_score` INT NOT NULL,
    `wards_placed` INT NOT NULL,
    `wards_killed` INT NOT NULL,
    `stealth_wards_placed` INT NOT NULL,
    `detector_wards_placed` INT NOT NULL,
    `vision_wards_bought` INT,
    `team_position` VARCHAR(20) NOT NULL,
    `individual_position` VARCHAR(20) NOT NULL,
    `physical_damage_dealt_to_champions` INT NOT NULL,
    `magic_damage_dealt_to_champions` INT NOT NULL,
    `true_damage_dealt_to_champions` INT NOT NULL,
    `total_damage_taken` INT NOT NULL,
    `double_kills` INT NOT NULL,
    `triple_kills` INT NOT NULL,
    `quadra_kills` INT NOT NULL,
    `penta_kills` INT NOT NULL,
    `win` BOOLEAN NOT NULL,
    `created_at` DATETIME NOT NULL,
    `modified_at` DATETIME NOT NULL,
    PRIMARY KEY (`participant_id`, `match_id`)
);

CREATE TABLE `participant_analysis` (
    `participant_id` BIGINT NOT NULL,
    `match_id` VARCHAR(20) NOT NULL,
    `damage_dealt_to_buildings` INT NOT NULL,
    `damage_dealt_to_objectives` INT NOT NULL,
    `damage_dealt_to_turrets` INT NOT NULL,
    `total_time_cc_dealt` INT NOT NULL,
    `jungle_cs_before_10_min` FLOAT NOT NULL,
    `lane_minions_first_10_min` INT NOT NULL,
    `scuttle_crab_kills` INT NOT NULL,
    `quick_solo_kills` INT NOT NULL,
    `kills_on_laners_early_jungle` INT NOT NULL,
    `stat_perks_defense` INT NOT NULL,
    `stat_perks_flex` INT NOT NULL,
    `stat_perks_offense` INT NOT NULL,
    `created_at` DATETIME NOT NULL,
    `modified_at` DATETIME NOT NULL,
    PRIMARY KEY (`participant_id`, `match_id`)
);

CREATE TABLE `participant_perk` (
    `participant_id` BIGINT NOT NULL,
    `match_id` VARCHAR(20) NOT NULL,
    `style_type` VARCHAR(10) NOT NULL,
    `style` INT NULL NOT NULL,
    `perk_id` INT NULL NOT NULL,
    `var1` INT NULL NOT NULL,
    `var2` INT NULL NOT NULL,
    `var3` INT NULL NOT NULL,
    `created_at` DATETIME NOT NULL,
    `modified_at` DATETIME NOT NULL,
    PRIMARY KEY (`participant_id`, `match_id`, `style_type`)
);
